name: Comp215 Autograder

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up Java11
      uses: actions/setup-java@v1
      with:
        java-version: 11
    - name: Build / Autograde
      run: bash rungrader.sh
